apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-custom-sc
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  type: gp2         # Or use 'gp3' if supported
  fsType: ext4
